export const FETCH_PERSONS_BY_PAGE_NUMBER_REQUEST = "FETCH_PERSONS_BY_PAGE_NUMBER";
export const CHANGE_CURRENT_PERSONS_PAGE_NUMBER = "CHANGE_CURRENT_PERSONS_PAGE_NUMBER";
export const LOAD_PERSONS_REQUEST = "LOAD_PERSONS_REQUEST";
export const LOAD_PERSONS_SUCCESS = "LOAD_PERSONS_SUCCESS";
export const LOAD_PERSON_SUCCESS = "LOAD_PERSON_SUCCESS";
export const LOAD_PERSONS_FAILURE = "LOAD_PERSONS_FAILURE";
