export const FETCH_PLANETS_BY_PAGE_NUMBER_REQUEST = "FETCH_PLANETS_BY_PAGE_NUMBER_REQUEST";
export const CHANGE_CURRENT_PLANETS_PAGE_NUMBER = "CHANGE_CURRENT_PLANETS_PAGE_NUMBER";
export const LOAD_PLANETS_REQUEST = "LOAD_PLANETS_REQUEST";
export const LOAD_PLANETS_SUCCESS = "LOAD_PLANETS_SUCCESS";
export const LOAD_PLANETS_FAILURE = "LOAD_PLANETS_FAILURE";