export const INITIALIZE_APP = "INITIALIZE_APP";
export const IS_INITIALIZED = "IS_INITIALIZED";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const SET_APP_INITIALIZED = "SET_APP_INITIALIZED";
