export const FETCH_STARSHIPS_BY_PAGE_NUMBER_REQUEST = "FETCH_STARSHIPS_BY_PAGE_NUMBER_REQUEST";
export const CHANGE_CURRENT_STARSHIPS_PAGE_NUMBER = "CHANGE_CURRENT_STARSHIPS_PAGE_NUMBER";
export const LOAD_STARSHIPS_REQUEST = "LOAD_STARSHIPS_REQUEST";
export const LOAD_STARSHIPS_SUCCESS = "LOAD_STARSHIPS_SUCCESS";
export const LOAD_STARSHIPS_FAILURE = "LOAD_STARSHIPS_FAILURE";