export const INIT_PROMO_REQUEST = "INIT_PROMO_REQUEST";
export const LOAD_PROMO_ERROR = "LOAD_PROMO_ERROR";

export const LOAD_PLANET_REQUEST = "LOAD_PLANET_REQUEST";
export const LOAD_PLANET_SUCCESS = "LOAD_PLANET_SUCCESS";
export const LOAD_PLANET_FAILURE = "LOAD_PLANET_FAILURE";

export const LOAD_PERSON_REQUEST = "LOAD_PERSON_REQUEST";
export const LOAD_PERSON_SUCCESS = "LOAD_PERSON_SUCCESS";
export const LOAD_PERSON_FAILURE = "LOAD_PERSON_FAILURE";

export const LOAD_STARSHIP_REQUEST = "LOAD_STARSHIP_REQUEST";
export const LOAD_STARSHIP_SUCCESS = "LOAD_STARSHIP_SUCCESS";
export const LOAD_STARSHIP_FAILURE = "LOAD_STARSHIP_FAILURE";

export const FETCH_RANDOM_PLANET_REQUEST = "FETCH_RANDOM_PLANET_REQUEST";

