export const INIT_PROMO_REQUEST = "INIT_PROMO_REQUEST";
export const LOAD_PROMO_ERROR = "LOAD_PROMO_ERROR";

export const LOAD_PLANET_REQUEST = "LOAD_PLANET_REQUEST";
export const LOAD_PLANET_SUCCESS = "LOAD_PLANET_SUCCESS";
export const LOAD_PLANET_FAILURE = "LOAD_PLANET_FAILURE";
export const FETCH_RANDOM_PLANET_REQUEST = "FETCH_RANDOM_PLANET_REQUEST";

